import * as THREE from 'three';

const canvas = document.querySelector('#garden');
const isMobile = matchMedia('(max-width: 700px), (pointer: coarse)').matches;
const renderer = new THREE.WebGLRenderer({ canvas, antialias: true, alpha: true });
renderer.setPixelRatio(Math.min(devicePixelRatio, isMobile ? 1.5 : 2));
renderer.setSize(innerWidth, innerHeight);
renderer.outputColorSpace = THREE.SRGBColorSpace;
renderer.toneMapping = THREE.ACESFilmicToneMapping;
renderer.toneMappingExposure = 1.25;

const scene = new THREE.Scene();
scene.fog = new THREE.FogExp2(0x160d1c, .07);
const camera = new THREE.PerspectiveCamera(36, innerWidth / innerHeight, .1, 100);
camera.position.set(0, .1, 12);
const world = new THREE.Group(); scene.add(world);

scene.add(new THREE.HemisphereLight(0xffd5df, 0x160d20, 1.6));
const key = new THREE.PointLight(0xff75a8, 4.5, 18); key.position.set(-3, 3, 5); scene.add(key);
const rim = new THREE.PointLight(0xb89bff, 3.5, 16); rim.position.set(4, -1, 3); scene.add(rim);

const palette = [0xff456e, 0xff83ad, 0xffd5df, 0xf5bd9f, 0xc89cf5, 0xfff1cf];
const flowerGroup = new THREE.Group(); world.add(flowerGroup);
const petalGeo = createPetalGeometry();
const centerGeo = new THREE.SphereGeometry(.11, 12, 10);
const stemMat = new THREE.MeshStandardMaterial({ color: 0x72505f, roughness: .55, metalness: .15 });
const flowers = [];
const rand = (a, b) => a + Math.random() * (b - a);
// Deterministic, smooth-looking variation: the composition is generated by
// equations, then given only a small organic perturbation rather than chaos.
const hash = n => {
  const x = Math.sin(n * 91.173 + 17.71) * 43758.5453123;
  return x - Math.floor(x);
};
const signedNoise = (n, a = 1) => (hash(n) * 2 - 1) * a;

function createPetalGeometry() {
  const shape = new THREE.Shape();
  shape.moveTo(0, 0);
  shape.bezierCurveTo(-.34, .08, -.47, .58, 0, 1.28);
  shape.bezierCurveTo(.47, .58, .34, .08, 0, 0);
  // A tiny bevel catches the light so petals no longer read as flat cards.
  const geometry = new THREE.ExtrudeGeometry(shape, { depth: .025, bevelEnabled: true, bevelThickness: .014, bevelSize: .012, bevelSegments: 2, curveSegments: 12 });
  geometry.translate(0, -.15, -.012);
  return geometry;
}

function heartPoint(t, scale = 1, depth = 0) {
  const x = 16 * Math.pow(Math.sin(t), 3);
  const y = 13 * Math.cos(t) - 5 * Math.cos(2*t) - 2 * Math.cos(3*t) - Math.cos(4*t);
  // Taller lobes and a clean lower point give the heart a more recognisable silhouette.
  const flutter = Math.sin(t * 7) * .014 + Math.cos(t * 13) * .008;
  return new THREE.Vector3(x * (.185 * scale + flutter), y * (.222 * scale + flutter) + .18, depth);
}
function addStem(end) {
  const start = new THREE.Vector3(end.x * .16, -3.35, -.25);
  const curve = new THREE.QuadraticBezierCurve3(start, new THREE.Vector3(end.x * .32, (start.y + end.y) * .52, -.4), end.clone().multiplyScalar(.95));
  const stem = new THREE.Mesh(new THREE.TubeGeometry(curve, 18, .018, 5, false), stemMat);
  flowerGroup.add(stem);
}
function makeFlower(position, size, color, delay) {
  const group = new THREE.Group(); group.position.copy(position);
  group.rotation.set(rand(-.22,.22), rand(-.22,.22), rand(-.5,.5));
  const petals = [], count = Math.round(rand(7, 9));
  const mat = new THREE.MeshStandardMaterial({ color, emissive: color, emissiveIntensity: .24, roughness: .38, metalness: .05, side: THREE.DoubleSide, transparent: true, opacity: .95 });
  const innerColor = new THREE.Color(color).lerp(new THREE.Color(0xffefd9), .30);
  const innerMat = new THREE.MeshStandardMaterial({ color: innerColor, emissive: color, emissiveIntensity: .34, roughness: .31, metalness: .08, side: THREE.DoubleSide, transparent: true, opacity: .97 });
  // Broad outer petals establish the flower; the shorter rotated inner ring adds depth.
  for (let i = 0; i < count; i++) {
    const petal = new THREE.Mesh(petalGeo, mat);
    const angle = (i / count) * Math.PI * 2 + rand(-.12,.12);
    petal.position.set(Math.cos(angle)*.055, Math.sin(angle)*.055, rand(-.04,.04));
    petal.rotation.set(rand(-.16,.16), rand(-.2,.2), angle - Math.PI/2);
    petal.userData = { angle, phase: rand(0, Math.PI*2), ring: 0, stagger: i % 2 };
    group.add(petal); petals.push(petal);
  }
  const innerCount = count - 2;
  for (let i = 0; i < innerCount; i++) {
    const petal = new THREE.Mesh(petalGeo, innerMat);
    const angle = (i / innerCount) * Math.PI * 2 + Math.PI / innerCount + rand(-.08,.08);
    petal.position.set(Math.cos(angle)*.025, Math.sin(angle)*.025, .045 + rand(-.02,.025));
    petal.rotation.set(rand(-.12,.12), rand(-.12,.12), angle - Math.PI/2);
    petal.userData = { angle, phase: rand(0, Math.PI*2), ring: 1, stagger: i % 2 };
    group.add(petal); petals.push(petal);
  }
  const inner = new THREE.Mesh(centerGeo, new THREE.MeshStandardMaterial({ color: 0xffedbe, emissive: 0xffa85a, emissiveIntensity: 1.1, roughness: .25 }));
  const core = new THREE.Mesh(new THREE.SphereGeometry(.055, 10, 8), new THREE.MeshBasicMaterial({ color: 0xfff4c7, transparent: true, opacity: .9 }));
  core.position.z = .09; group.add(inner, core); flowerGroup.add(group); addStem(position);
  flowers.push({ group, petals, inner, core, size, delay, bob: rand(0, 6.28), baseY: position.y });
}

// A parametric heart defines the outer bouquet. Its spacing is intentional,
// with a phase shift to keep the lower point from becoming mechanically even.
const edgeCount = 34;
for (let i = 0; i < edgeCount; i++) {
  const u = i / edgeCount;
  const t = u * Math.PI * 2 + .05 * Math.sin(u * Math.PI * 6);
  const radius = 1 + signedNoise(i + 3, .065);
  const p = heartPoint(t, radius, signedNoise(i + 9, .28));
  const colorIndex = Math.floor(hash(i * 4.13) * palette.length);
  makeFlower(p, .39 + hash(i * 8.7) * .19, palette[colorIndex], .9 + i * .24);
}
// The centre uses a golden-angle phyllotaxis distribution. That is the same
// botanical spacing visible in sunflower heads and gives this heart a living core.
const coreCount = 32, goldenAngle = Math.PI * (3 - Math.sqrt(5));
for (let i = 0; i < coreCount; i++) {
  const radius = Math.sqrt((i + .5) / coreCount) * .82;
  const t = i * goldenAngle + .55 * Math.sin(i * .73);
  const p = heartPoint(t, radius, signedNoise(i + 41, .33));
  p.x *= .78; p.y = p.y * .74 - .12;
  const colorIndex = Math.floor(hash(i * 2.41 + 100) * palette.length);
  makeFlower(p, .29 + hash(i * 5.31) * .2, palette[colorIndex], 2.2 + i * .18);
}

function makePoints(count, size, colorChoices, range) {
  // This is a GPU-friendly particle field: the same idea as your `phi`,
  // `theta`, `randoms`, `scales`, `colors` and `speeds` example.
  const positions = new Float32Array(count * 3);
  const basePositions = new Float32Array(count * 3);
  const colors = new Float32Array(count * 3);
  const randoms = new Float32Array(count);
  const randoms1 = new Float32Array(count);
  const scales = new Float32Array(count);
  const speeds = new Float32Array(count);
  for (let i = 0; i < count; i++) {
    const phi = Math.random() * Math.PI * 2;
    const theta = Math.acos(2 * Math.random() - 1);
    const radius = range * (.22 + Math.random() * .78);
    // Spherical distribution, stretched vertically to embrace the floral heart.
    const x = radius * Math.sin(theta) * Math.cos(phi);
    const y = radius * Math.cos(theta) * .78;
    const z = radius * Math.sin(theta) * Math.sin(phi) - 1.2;
    positions.set([x, y, z], i * 3);
    basePositions.set([x, y, z], i * 3);
    randoms[i] = Math.random();
    randoms1[i] = Math.random();
    scales[i] = Math.random() * .35;
    speeds[i] = .16 + Math.random() * .48;
    const colorIndex = Math.floor(Math.random() * colorChoices.length);
    const color = new THREE.Color(colorChoices[colorIndex]);
    colors[i * 3] = color.r;
    colors[i * 3 + 1] = color.g;
    colors[i * 3 + 2] = color.b;
  }
  const g = new THREE.BufferGeometry();
  g.setAttribute('position', new THREE.BufferAttribute(positions,3));
  g.setAttribute('color', new THREE.BufferAttribute(colors,3));
  g.setAttribute('aRandom', new THREE.BufferAttribute(randoms,1));
  g.setAttribute('aRandom1', new THREE.BufferAttribute(randoms1,1));
  g.setAttribute('aScale', new THREE.BufferAttribute(scales,1));
  g.setAttribute('aSpeed', new THREE.BufferAttribute(speeds,1));
  const m = new THREE.ShaderMaterial({
    transparent: true, depthWrite: false, blending: THREE.AdditiveBlending,
    uniforms: { uTime: { value: 0 }, uOpacity: { value: size < .04 ? .72 : .95 }, uPointSize: { value: size < .04 ? 8.0 : 14.0 } },
    vertexShader: `
      uniform float uTime; uniform float uPointSize;
      attribute vec3 color; attribute float aRandom; attribute float aRandom1; attribute float aScale; attribute float aSpeed;
      varying vec3 vColor; varying float vAlpha;
      void main() {
        vec3 p = position;
        float phase = uTime * aSpeed + aRandom * 6.28318;
        // Every light has its own orbital curve, controlled by its arrays.
        p.x += cos(phase) * (.05 + aScale * .22);
        p.y += sin(phase * 1.37 + aRandom1 * 6.28) * (.07 + aScale * .30);
        p.z += sin(phase * .72) * (.04 + aScale * .16);
        vec4 mvPosition = modelViewMatrix * vec4(p, 1.0);
        gl_PointSize = uPointSize * (1.0 + aScale * 2.5 + sin(phase) * .24) * (24.0 / -mvPosition.z);
        gl_Position = projectionMatrix * mvPosition;
        vColor = color; vAlpha = .42 + aRandom * .58;
      }`,
    fragmentShader: `
      uniform float uOpacity; varying vec3 vColor; varying float vAlpha;
      void main() {
        float d = length(gl_PointCoord - .5);
        float glow = smoothstep(.5, .05, d);
        float core = smoothstep(.20, .0, d);
        gl_FragColor = vec4(vColor * (glow + core * .8), glow * vAlpha * uOpacity);
      }`
  });
  const points = new THREE.Points(g,m);
  points.userData = { basePositions, randoms, randoms1, scales, speeds };
  return points;
}

// A separate mathematical sculpture: particles begin as an orbiting cloud and
// are pulled onto the parametric heart before the physical flowers finish blooming.
function makeHeartConstellation(count) {
  const target = new Float32Array(count * 3), start = new Float32Array(count * 3);
  const colors = new Float32Array(count * 3), phase = new Float32Array(count), delay = new Float32Array(count), scale = new Float32Array(count);
  for (let i = 0; i < count; i++) {
    const t = Math.random() * Math.PI * 2;
    const radius = Math.sqrt(Math.random()) * 1.04;
    const p = heartPoint(t, radius, signedNoise(i + 290, .42) * (1 - radius * .45));
    target.set([p.x, p.y, p.z], i * 3);
    // A spherical start state, like the phi/theta construction discussed above.
    const phi = Math.random() * Math.PI * 2, theta = Math.acos(2 * Math.random() - 1), r = 3.8 + Math.random() * 1.8;
    start.set([r * Math.sin(theta) * Math.cos(phi), r * Math.cos(theta), r * Math.sin(theta) * Math.sin(phi) - 1.8], i * 3);
    const color = new THREE.Color(palette[Math.floor(hash(i * 3.7) * palette.length)]);
    colors.set([color.r, color.g, color.b], i * 3);
    phase[i] = Math.random() * Math.PI * 2;
    delay[i] = Math.random() * .68;
    scale[i] = .25 + Math.random() * .75;
  }
  const geometry = new THREE.BufferGeometry();
  geometry.setAttribute('position', new THREE.BufferAttribute(target, 3));
  geometry.setAttribute('aStart', new THREE.BufferAttribute(start, 3));
  geometry.setAttribute('color', new THREE.BufferAttribute(colors, 3));
  geometry.setAttribute('aPhase', new THREE.BufferAttribute(phase, 1));
  geometry.setAttribute('aDelay', new THREE.BufferAttribute(delay, 1));
  geometry.setAttribute('aScale', new THREE.BufferAttribute(scale, 1));
  const material = new THREE.ShaderMaterial({
    transparent: true, depthWrite: false, blending: THREE.AdditiveBlending,
    uniforms: { uTime: { value: 0 }, uBuild: { value: 0 } },
    vertexShader: `
      uniform float uTime; uniform float uBuild;
      attribute vec3 aStart; attribute vec3 color; attribute float aPhase; attribute float aDelay; attribute float aScale;
      varying vec3 vColor; varying float vLife;
      void main() {
        float arrive = smoothstep(aDelay, min(aDelay + .32, 1.0), uBuild);
        vec3 cloud = aStart;
        float orbit = uTime * .24 + aPhase;
        cloud.x += cos(orbit) * .18; cloud.y += sin(orbit * 1.31) * .15;
        vec3 p = mix(cloud, position, arrive);
        // After arriving, each point breathes rather than sitting still.
        p.z += sin(uTime * .7 + aPhase) * .045 * arrive;
        p.x += cos(uTime * .46 + aPhase) * .025 * arrive;
        vec4 mv = modelViewMatrix * vec4(p, 1.0);
        gl_PointSize = (2.3 + aScale * 4.8 + sin(uTime + aPhase) * .7) * (25.0 / -mv.z);
        gl_Position = projectionMatrix * mv; vColor = color; vLife = arrive;
      }`,
    fragmentShader: `
      varying vec3 vColor; varying float vLife;
      void main() {
        float d = length(gl_PointCoord - .5);
        float halo = smoothstep(.5, .02, d);
        gl_FragColor = vec4(vColor * halo * 1.35, halo * (.18 + vLife * .58));
      }`
  });
  const points = new THREE.Points(geometry, material); world.add(points);
  return points;
}
const constellation = makeHeartConstellation(isMobile ? 1800 : 3200);
const dust = makePoints(isMobile ? 300 : 520, .025, palette, 5.5); scene.add(dust);
const sparkles = makePoints(isMobile ? 75 : 120, .055, [0xffe8c5,0xffacd0,0xdcc5ff], 4.3); scene.add(sparkles);

const trails = new THREE.Group(); world.add(trails);
for (let j=0;j<3;j++) {
  const pts=[]; for(let i=0;i<130;i++) { const a=(i/129)*Math.PI*2; const wobble = .16 * Math.sin(a * 3 + j * 1.8); pts.push(new THREE.Vector3(Math.cos(a*1.01+j*.07)*(3.1+j*.22+wobble), Math.sin(a*1.98+j*.05)*(1.08+j*.1), -1.4 + Math.sin(a*3+j)*.28)); }
  const geo=new THREE.BufferGeometry().setFromPoints(pts); const line=new THREE.Line(geo,new THREE.LineBasicMaterial({color:j===1?0xd8a5ff:0xff9ab9,transparent:true,opacity:.15,blending:THREE.AdditiveBlending})); line.rotation.set(rand(-.26,.26),rand(-.18,.18),rand(0,6.28)); trails.add(line);
}

const detached = [];
for (let i=0;i<(isMobile ? 16 : 28);i++) { const p=new THREE.Mesh(petalGeo,new THREE.MeshBasicMaterial({color:palette[i%palette.length],transparent:true,opacity:rand(.25,.7),side:THREE.DoubleSide})); p.scale.setScalar(rand(.07,.15)); p.position.set(rand(-4.5,4.5),rand(-3.6,4),rand(-1,2)); p.rotation.set(rand(0,6),rand(0,6),rand(0,6)); scene.add(p); detached.push({p, velocity:new THREE.Vector3(rand(-.004,.004),rand(-.008,-.002),rand(-.003,.003)), spin:rand(-.025,.025)}); }

const pointer = new THREE.Vector2(); addEventListener('pointermove', e => pointer.set((e.clientX/innerWidth-.5), (e.clientY/innerHeight-.5)));
const clock = new THREE.Clock();
function animate() {
  const t=clock.getElapsedTime();
  constellation.material.uniforms.uTime.value = t;
  constellation.material.uniforms.uBuild.value = THREE.MathUtils.smootherstep(t, .5, 8.7);
  constellation.rotation.z = Math.sin(t * .09) * .018;
  flowerGroup.rotation.z = Math.sin(t*.42)*.025; flowerGroup.rotation.x = Math.sin(t*.31)*.018;
  flowers.forEach(f => {
    const bloom = THREE.MathUtils.smoothstep(t, f.delay, f.delay + 3.35);
    const unfurl = THREE.MathUtils.smootherstep(t, f.delay + .4, f.delay + 4.15);
    f.group.scale.setScalar(Math.max(.001, bloom));
    f.group.position.y = f.baseY + Math.sin(t * .34 + f.bob) * .026;
    f.group.rotation.z += Math.sin(t * .12 + f.bob) * .00012;
    f.petals.forEach(p => {
      const ring = p.userData.ring;
      const growth = .22 + unfurl * .78;
      const width = f.size * (ring ? .56 : .82) * (p.userData.stagger ? .93 : 1.06);
      const length = f.size * (ring ? .65 : 1.00) * growth;
      p.scale.set(width, length, 1);
      p.rotation.x = Math.sin(t * .29 + p.userData.phase) * (.09 + ring * .05) + (1 - unfurl) * (ring ? -.42 : -.76);
    });
    f.inner.scale.setScalar(.36 + unfurl * .8);
    f.core.scale.setScalar(.45 + unfurl * .95);
  });
  // Motion is calculated in the GPU shader from the per-particle arrays.
  [dust, sparkles].forEach((field, fieldIndex) => {
    field.material.uniforms.uTime.value = t * .55;
    // Stars accumulate as the flowers arrive, rather than appearing all at once.
    field.material.uniforms.uOpacity.value = (fieldIndex ? .95 : .72) * THREE.MathUtils.smootherstep(t, 1.5, 8.8);
    field.rotation.y = t * (fieldIndex ? -.012 : .006);
  });
  trails.rotation.z=t*.012;
  detached.forEach(({p,velocity,spin})=>{p.position.add(velocity);p.rotation.z+=spin;p.rotation.y+=spin*.5;if(p.position.y<-4.5){p.position.y=4.3;p.position.x=rand(-4.5,4.5);}});
  camera.position.x += ((pointer.x*.32 + Math.sin(t*.075)*.22)-camera.position.x)*.008;
  camera.position.y += ((-.05-pointer.y*.16+Math.cos(t*.09)*.12)-camera.position.y)*.008;
  camera.lookAt(0,-.05,0); renderer.render(scene,camera); requestAnimationFrame(animate);
}
addEventListener('resize',()=>{camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();renderer.setPixelRatio(Math.min(devicePixelRatio, isMobile ? 1.5 : 2));renderer.setSize(innerWidth,innerHeight);});
animate();
